CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "display_name" varchar(80) NOT NULL,
  "password_hash" varchar(255),
  "expiry_alert_days" smallint NOT NULL DEFAULT 2,
  "auto_dispose_enabled" boolean NOT NULL DEFAULT true,
  "shopping_reminder_enabled" boolean NOT NULL DEFAULT false,
  "push_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);
ALTER TABLE user_sessions ADD CONSTRAINT fk_auth_test_user FOREIGN KEY (user_id) REFERENCES users(id);
