-- JPA가 매핑하지 않는 조회용 테이블. docs/vium.sql의 정의를 그대로 사용한다.
CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "display_name" varchar(80) NOT NULL,
  "password_hash" varchar(255),
  "expiry_alert_days" smallint NOT NULL DEFAULT 2,
  "auto_dispose_enabled" boolean NOT NULL DEFAULT true,
  "shopping_reminder_enabled" boolean NOT NULL DEFAULT false,
  "push_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "ingredient_categories" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(60) UNIQUE NOT NULL,
  "parent_id" smallint
);
