name: " 기능 개발"
description: "새 기능/엔드포인트 구현"
title: "[FEAT] "
labels: ["feat"]
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      placeholder: |
        예) 재료 등록/조회 API 구현
        - POST /api/me/ingredients
        - GET /api/me/ingredients
    validations:
      required: true
