CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "display_name" varchar(80) NOT NULL,
  "password_hash" varchar(255),
  "expiry_alert_days" smallint NOT NULL DEFAULT 2,
  "auto_dispose_enabled" boolean NOT NULL DEFAULT true,
  "shopping_reminder_enabled" boolean NOT NULL DEFAULT false,
  "push_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "auth_providers" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(30) UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "user_auth_accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "auth_provider_id" smallint NOT NULL,
  "provider_user_key" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "user_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "refresh_token_hash" varchar(255) UNIQUE NOT NULL,
  "issued_at" timestamp NOT NULL,
  "expires_at" timestamp NOT NULL,
  "revoked_at" timestamp
);

CREATE TABLE "units" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(40) NOT NULL
);

CREATE TABLE "ingredient_categories" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(60) UNIQUE NOT NULL,
  "parent_id" smallint
);

CREATE TABLE "storage_methods" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(30) UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "purchase_sources" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(30) UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "item_statuses" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(40) NOT NULL
);

CREATE TABLE "event_sources" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(40) NOT NULL
);

CREATE TABLE "ingredient_catalog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" smallint,
  "default_unit_id" smallint NOT NULL,
  "name" varchar(120) NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "expiry_estimation_rules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingredient_catalog_id" bigint NOT NULL,
  "storage_method_id" smallint NOT NULL,
  "shelf_life_days" int NOT NULL,
  "source" varchar(80),
  "effective_from" date NOT NULL,
  "effective_to" date
);

CREATE TABLE "purchases" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "purchase_source_id" smallint,
  "image_url" varchar(500),
  "ocr_status" varchar(20) NOT NULL DEFAULT 'none',
  "total_amount" numeric(12,2),
  "purchased_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "purchase_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchase_id" bigint NOT NULL,
  "ingredient_catalog_id" bigint,
  "raw_name" varchar(200),
  "quantity" numeric(12,3) NOT NULL,
  "unit_id" smallint NOT NULL,
  "unit_price" numeric(12,2),
  "amount" numeric(12,2)
);

CREATE TABLE "inventory_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "ingredient_catalog_id" bigint,
  "purchase_item_id" bigint,
  "custom_name" varchar(120),
  "status_id" smallint NOT NULL,
  "storage_method_id" smallint,
  "unit_id" smallint NOT NULL,
  "initial_quantity" numeric(12,3) NOT NULL,
  "remaining_quantity" numeric(12,3) NOT NULL,
  "amount" numeric(12,2),
  "purchased_on" date,
  "expires_on" date,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  CONSTRAINT "chk_inventory_items_identity" CHECK ("ingredient_catalog_id" IS NOT NULL OR "custom_name" IS NOT NULL)
);

CREATE TABLE "consumption_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_item_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "event_type" varchar(20) NOT NULL,
  "event_source_id" smallint NOT NULL,
  "quantity" numeric(12,3) NOT NULL,
  "amount" numeric(12,2),
  "occurred_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "type" varchar(30) NOT NULL,
  "inventory_item_id" bigint,
  "title" varchar(120) NOT NULL,
  "body" varchar(500),
  "scheduled_at" timestamp NOT NULL,
  "sent_at" timestamp,
  "read_at" timestamp,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "shopping_list_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "ingredient_catalog_id" bigint,
  "custom_name" varchar(120),
  "suggested_quantity" numeric(12,3),
  "unit_id" smallint,
  "reason" varchar(200),
  "is_checked" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "recipes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "description" varchar(1000),
  "source" varchar(120),
  "created_at" timestamp NOT NULL
);

CREATE TABLE "recipe_ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipe_id" bigint NOT NULL,
  "ingredient_catalog_id" bigint NOT NULL
);

CREATE TABLE "recipe_suggestions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "recipe_id" bigint NOT NULL,
  "suggested_at" timestamp NOT NULL,
  "reason" varchar(200)
);

CREATE UNIQUE INDEX ON "users" ("email");

CREATE UNIQUE INDEX ON "user_auth_accounts" ("auth_provider_id", "provider_user_key");

CREATE INDEX ON "user_auth_accounts" ("user_id");

CREATE INDEX ON "user_sessions" ("user_id");

CREATE INDEX ON "ingredient_categories" ("parent_id");

CREATE UNIQUE INDEX ON "ingredient_catalog" ("name");

CREATE INDEX ON "ingredient_catalog" ("category_id");

CREATE UNIQUE INDEX ON "expiry_estimation_rules" ("ingredient_catalog_id", "storage_method_id", "effective_from");

CREATE INDEX ON "purchases" ("user_id");

CREATE INDEX ON "purchase_items" ("purchase_id");

CREATE INDEX ON "purchase_items" ("ingredient_catalog_id");

CREATE INDEX ON "inventory_items" ("user_id");

CREATE INDEX ON "inventory_items" ("user_id", "status_id");

CREATE INDEX ON "inventory_items" ("user_id", "expires_on");

CREATE INDEX ON "inventory_items" ("ingredient_catalog_id");

CREATE INDEX ON "consumption_events" ("inventory_item_id");

CREATE INDEX ON "consumption_events" ("user_id", "event_type", "occurred_at");

CREATE INDEX ON "notifications" ("user_id", "scheduled_at");

CREATE INDEX ON "notifications" ("inventory_item_id");

CREATE INDEX ON "shopping_list_items" ("user_id");

CREATE INDEX ON "shopping_list_items" ("ingredient_catalog_id");

CREATE UNIQUE INDEX ON "recipe_ingredients" ("recipe_id", "ingredient_catalog_id");

CREATE INDEX ON "recipe_suggestions" ("user_id", "suggested_at");

CREATE INDEX ON "recipe_suggestions" ("recipe_id");

COMMENT ON COLUMN "users"."password_hash" IS '소셜 전용 계정이면 NULL 허용';

COMMENT ON COLUMN "users"."expiry_alert_days" IS 'D-N 임박 알림 기준';

COMMENT ON COLUMN "purchases"."ocr_status" IS 'none/pending/done/failed (image_url이 NULL이면 영수증 없는 구매)';

COMMENT ON COLUMN "purchase_items"."raw_name" IS '영수증 원문 품목명(미매칭 대비)';

COMMENT ON COLUMN "inventory_items"."custom_name" IS '카탈로그에 없는 재료 직접 입력용';

COMMENT ON COLUMN "inventory_items"."amount" IS '낭비 금액 집계용 취득가';

COMMENT ON COLUMN "inventory_items"."expires_on" IS '자동 추정값, 사용자가 수정 가능';

COMMENT ON COLUMN "consumption_events"."event_type" IS 'consumed / disposed';

COMMENT ON COLUMN "consumption_events"."event_source_id" IS 'manual / auto_estimated';

COMMENT ON COLUMN "consumption_events"."quantity" IS '게이지로 조절한 처리량';

COMMENT ON COLUMN "consumption_events"."amount" IS '해당 처리량의 금액(낭비 집계용)';

COMMENT ON COLUMN "notifications"."type" IS 'expiry / consume_check / shopping_reminder';

COMMENT ON COLUMN "shopping_list_items"."suggested_quantity" IS '낭비 이력 기반 제안량';

COMMENT ON COLUMN "shopping_list_items"."reason" IS '예: ''지난달 절반을 버림 → 절반만''';

COMMENT ON COLUMN "recipe_suggestions"."reason" IS '임박 재료 조합 근거';

ALTER TABLE "user_auth_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_auth_accounts" ADD FOREIGN KEY ("auth_provider_id") REFERENCES "auth_providers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingredient_categories" ADD FOREIGN KEY ("parent_id") REFERENCES "ingredient_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingredient_catalog" ADD FOREIGN KEY ("category_id") REFERENCES "ingredient_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingredient_catalog" ADD FOREIGN KEY ("default_unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expiry_estimation_rules" ADD FOREIGN KEY ("ingredient_catalog_id") REFERENCES "ingredient_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expiry_estimation_rules" ADD FOREIGN KEY ("storage_method_id") REFERENCES "storage_methods" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchases" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchases" ADD FOREIGN KEY ("purchase_source_id") REFERENCES "purchase_sources" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_items" ADD FOREIGN KEY ("purchase_id") REFERENCES "purchases" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_items" ADD FOREIGN KEY ("ingredient_catalog_id") REFERENCES "ingredient_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_items" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("ingredient_catalog_id") REFERENCES "ingredient_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("purchase_item_id") REFERENCES "purchase_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("status_id") REFERENCES "item_statuses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("storage_method_id") REFERENCES "storage_methods" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory_items" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consumption_events" ADD FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consumption_events" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consumption_events" ADD FOREIGN KEY ("event_source_id") REFERENCES "event_sources" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_items" ADD FOREIGN KEY ("ingredient_catalog_id") REFERENCES "ingredient_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "shopping_list_items" ADD FOREIGN KEY ("unit_id") REFERENCES "units" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("ingredient_catalog_id") REFERENCES "ingredient_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipe_suggestions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipe_suggestions" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("id") DEFERRABLE INITIALLY IMMEDIATE;
